AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 3
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ub-code-sam/49eeb61f5815578901ca3b3dfe89716d
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
          REGION_NAME:
            Ref: AWS::Region
      Events:
        HelloWorldSamApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: Table
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: ub-HelloWorld
      PrimaryKey:
        Name: greeting
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
